// 파일 확장자와 언어 매핑
export const LANGUAGE_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'tsx',
  js: 'javascript',
  jsx: 'jsx',
  json: 'json',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  html: 'html',
  xml: 'xml',
  md: 'markdown',
  yaml: 'yaml',
  yml: 'yaml',
  py: 'python',
  java: 'java',
  cpp: 'cpp',
  c: 'c',
  sh: 'bash',
  bash: 'bash',
  sql: 'sql',
  php: 'php',
  rb: 'ruby',
  go: 'go',
  rs: 'rust',
  vue: 'vue',
  svelte: 'svelte',
};

